### ISSUE TITLE
Issue with configuration

### ISSUE THREAD

**Issue by simmia24** [dagu-dev/dagu#421]
Encountering configuration issues while attempting to use environment variables for configuration. 
Authentication is not functioning as expected with this approach. Although using admin YAML resolves the issue, but unable to start a DAG through the UI.

**Comment by yohamta** [comment]
Hi @simmia24, can you please share the reproducible `admin.yaml` and `dag.yaml`?

**Comment by simmia24** [comment]
[configs.zip](https://github.com/yohamta/dagu/files/11074657/configs.zip)


Hi @yohamta  

I have attached admin.yaml with dag file.

**Comment by yohamta** [comment]
@simmia24 Thank you for attaching the file! I noticed something in your admin.yaml file that might be causing an issue. Could you try commenting out the line below and see if that solves the problem?
```diff
- command: /Users/simranarora/dagu/bin/dagu                 # default: dagu
+ # command: /Users/simranarora/dagu/bin/dagu                 # default: dagu
```

**Comment by simmia24** [comment]
Hi @yohamta  
Issue is resolved with your solution. Thank You for your help.
Can you provide information on how the "command" key was causing an issue? It would be much appreciated if you could elaborate on this.

**Comment by yohamta** [comment]
@simmia24  I'm glad to hear that the issue has been resolved with my solution. Regarding the "command" key in the config, we plan to remove it as it is currently unnecessary. This setting can cause issues if the dagu path is different or if there are insufficient permissions. We understand that errors can be hard to understand, so we're working to improve this in the future. If you have any further issues or questions, please don't hesitate to create another issue. Thanks!

**Comment by dat-adi** [comment]
Hi @yohamta, while that solution may have resolved the issue for simran. I did notice that there was a difference in the expected environment variables in the source code as compared to the documentation.

For reference,
The expected environment variables from the source code are the following,
```python
	viper.BindEnv("isBasicAuth", "DAGU_IS_BASICAUTH")
	viper.BindEnv("basicAuthUsername", "DAGU_BASICAUTH_USERNAME")
	viper.BindEnv("basicAuthPassword", "DAGU_BASICAUTH_PASSWORD")
```

However, the mentioned environment variables in the documentation are as given,
![image](https://github.com/dagu-dev/dagu/assets/31721284/647162b4-c6b0-4e01-ba03-8576204a1c90)
src: https://dagu.readthedocs.io/en/latest/auth.html

Shall I drop a PR to fix the docs?

**Comment by yohamta** [comment]
Hey @dat-adi 👋 Thank you for spotting the issue! I'd really appreciate it if you could submit an pull request to fix the document fix 🙏 You can find the file here:
https://github.com/dagu-dev/dagu/blob/main/docs/source/config.rst

**Comment by dat-adi** [comment]
Hi @yohamta, I've raised the PR for the same.
Hope it helps! :D
