### ISSUE TITLE
REST API is Responding as HTML in version 1.12.4

### ISSUE THREAD

**Issue by jheredianet** [dagu-dev/dagu#484]
Hi, I've realized that API is responding as HTML not as "application/json" as it should be

I'm calling the REST API as:

GET
   https://myserver/dags
HEADERS
   Accept: application/json

The response is:

```
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dagu</title>
    <script>
    function getConfig() {
      return {
        apiURL: "/api/v1",
        title: "Dagu",
        navbarColor: "",
        version: "1.12.4",
      }
    }
  </script>
    <script defer="defer" src="/assets/bundle.js?v=1.12.4"></script>
  </head>
  <body>

    <div id="root"></div>

  </body>

</html>
```

In version [v1.11.0](https://github.com/dagu-dev/dagu/releases/tag/v1.11.0) it works as expected.

**Comment by yohamta** [comment]
Hi 👋 the API path is moved to `/api/v1/dags` in v1.12.x. Would it be possible to use the newer path?

Here is the Open API schema for the API.
https://github.com/dagu-dev/dagu/blob/main/swagger.yaml

**Comment by jheredianet** [comment]
Oh, I see, thank you.
I was reading this documentation https://dagu.readthedocs.io/en/latest/rest.html
But it's not updated as I can see. 

I look further to adapt what I have already.
