### ISSUE TITLE
Any Issues? Let me know!

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#500]
I feels like there might be some issues that I have not noticed for the latest version.
I’d really appreciate it if you could drop a comment if there’s any odd in behavior, doc, or anything that you’ve noticed.
Thanks!

**Comment by alexandru-bagu** [comment]
Hi,

I am trying to figure out how to set a timeout on DAGs/steps however the option that is configurable, MaxCleanUpTimeSec, does not seem to work. I have been testing on v1.12.7.

**Comment by yohamta** [comment]
@alexandru-bagu Thanks for the question. `MaxCleanUpTimeSec` option is meant for the period before terminating child processes when a DAG receives a TERM signal. Unfortunately, there isn't a direct configuration option for setting a timeout at the moment.
As a workaround, you could consider creating a step within your DAG that monitors runtime and actively terminates the DAG process under specific conditions.
Hope this helps!

**Comment by yohamta** [comment]
Created an issue for timeout feature:
- #565
