### ISSUE TITLE
Implementing Token-Based Authentication

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#505]
Current authentication method: Basic Authentication.
Proposed enhancement: Token-Based Authentication.
Motivation: To make it easier to use the API, especially for JavaScript applications running in a browser from a different domain. Refer to the discussion here for more context: [GitHub Discussion #501](https://github.com/dagu-dev/dagu/discussions/501).

To-do:

- [x] Implement the configuration option for token-based authentication (`AuthToken` field).
- [x] Create an environment variable (`DAGU_AUTH_TOKEN`) for token management.
- [x] Implement middleware for token-based authentication.
- [ ] Adjust basic auth middleware to recognize and skip requests with valid tokens.
- [ ] Test that the Web UI remains unaffected by these changes.

**Comment by smekuria1** [comment]
Hello, I would like to tackle this issue.

**Comment by yohamta** [comment]
Hello, that's great! thanks!
