### ISSUE TITLE
Unable to run arbitrary code snippets using the "script" directive

### ISSUE THREAD

**Issue by ohourcard** [dagu-dev/dagu#510]
Hello,

I'm unable to run arbitrary code snippets using the "script" directive.

Sample (simple) DAG:

```
steps:
  - name: step 1
    command: bash
    script: |
      echo "hello world"
```

Encountered error (whatever shell or other command is declared in "command"):

+---+--------+---------------------+---------------------+--------+---------+------------------+
| # | STEP   | STARTED AT          | FINISHED AT         | STATUS | COMMAND | ERROR            |
+---+--------+---------------------+---------------------+--------+---------+------------------+
| 1 | step 1 | 2023-12-30 15:07:44 | 2023-12-30 15:07:44 | **failed** | **bash**    | **invalid argument** |
+---+--------+---------------------+---------------------+--------+---------+------------------+

Any clue of what's going wrong?

Thanks,
Oliver

**Comment by yohamta** [comment]
Hello, thanks for the question.
I tried the same DAG on my local computer and it seems working fine.
Would you mind share the Dagu version are you using?

![image](https://github.com/dagu-dev/dagu/assets/1475839/82ef4fb6-a1a8-49c2-ade5-2081760b8ec7)

**Comment by ohourcard** [comment]
Thanks for your answer!
I'm using dagu v1.12.7

**Comment by yohamta** [comment]
Thanks for letting me know!
Internally, Dagu works this way:
- write the script to the temp file.
- execute the command passing the temp file name as the single parameter.

So, I think chances are there's an issue of the `bash` command in your environment.
Could you please check if `bash` command works by running the command `bash <hello world script>` in your computer.

**Comment by ohourcard** [comment]
Yohamta,

I don't think the issue is related to the interpreter or any other command (I've tried many combination of bash/zsh or any command): in fact, since I use the "script" directive I've got this error (the "command" directive works fine unitarily).

Is there any chance that the temp file may be deleted before being executed?

### The detail of my environment follows:

DEBIAN:
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

BASH:
debian@dagu ➜  ~ bash --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

### Running a sample bash script from the host

Sample script

```
#/bin/bash
echo "hello world"
```

dagu@dagu$ bash test.sh
hello world

dagu@dagu$ bash | echo test
test

Can you lead me to the part of the code handling that temp file creation ? I'm not pretty familiar with Go...

Regards,
Oliver

**Comment by ohourcard** [comment]
After further investigations, this seems to be related to permissions on my environment.

When I force the working dir on the DAG's step (e.g. /tmp), the task is perfectly executed:

![image](https://github.com/dagu-dev/dagu/assets/1030339/64db070b-5125-4c45-bceb-63543a020102)

![image](https://github.com/dagu-dev/dagu/assets/1030339/3670540e-6605-46af-89cc-5be4faabd739)

As I can see in the repository, the module in charge of generating the tempfile is "internal/schedule/node" and expecially the function "setupScript". Maybe it will be a good idea to add/perform addtional checks on the generated temporary file?

I'll invetigate further to identify those permissions issues.

Regards,
Oliver

**Comment by yohamta** [comment]
Hi Oliver, thanks for your thorough investigation and the great suggestion!

You're right about the "internal/schedule/node" is responsible for creating a tempfile.

> Maybe it will be a good idea to add/perform addtional checks on the generated temporary file?
I agree, it seems definitely better and we can make the error message to be more user-friendly.
