### ISSUE TITLE
Failed to build Dagu on a freshly cloned repo

### ISSUE THREAD

**Issue by rafiramadhana** [dagu-dev/dagu#514]
How to reproduce
1. Clone [dagu](https://github.com/dagu-dev/dagu)
2. Run `make build`

When running `make build`, I ran into this issue (I omit some part of the logs for brevity)
```
➜  dagu git:(main) make build
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...

...

rm: cannot remove './service/frontend/assets/*.js': No such file or directory
make: *** [Makefile:72: build-ui] Error 1
```

To solve this, I think we can update the Makefile target `build-ui` by doing `rm -f`
```
build-ui:
	@cd ui; \
		yarn && yarn build

	@rm -f ./service/frontend/assets/*.js
	@rm -f ./service/frontend/assets/*.woff
	@rm -f ./service/frontend/assets/*.woff2

	@cp ui/dist/*.js ./service/frontend/assets/
	@cp ui/dist/*.woff ./service/frontend/assets/
	@cp ui/dist/*.woff2 ./service/frontend/assets/
```
https://github.com/dagu-dev/dagu/blob/main/Makefile#L70C1-L80C48

Thx!

**Comment by yohamta** [comment]
Hi, thanks a lot for submitting the PR. I completely agree, let's update the Makefile.

**Comment by rafiramadhana** [comment]
> let's update the Makefile.

Ok, I will submit a PR
