### ISSUE TITLE
Add Internationalization to the Web UI

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#516]
Our UI is currently available only in English. We would like to make Dagu usable by people who speak different languages.

Here's the [UI code](https://github.com/dagu-dev/dagu/tree/main/ui).

- [ ] Install [React i18next](https://react.i18next.com/)
- [ ] Set up language detection to automatically select the user's language.
- [ ] Create translation files for Chinese.
- [ ] Create translation files for Japanese.
- [ ] Create translation for other languages.

**Comment by ohourcard** [comment]
Available to perform fr-FR translations (which can be replicated to fr-CH/fr-BE).
