### ISSUE TITLE
Add Multilingual Support to Sphinx Documentation

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#517]
To make it accessible to a broader audience, we're planning to add multilingual support.

Tasks:
- [ ] Set up [Sphinx i18n feature](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html).
- [ ] Create initial translation files for Japanese. 
- [ ] Create initial translation files for Chinese.

**Comment by ohourcard** [comment]
Available to perform fr-FR translations (which can be replicated to fr-CH/fr-BE).
