### ISSUE TITLE
Update REST API Documentation with OpenAPI Spec

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#518]
Our current [REST API docs](https://dagu.readthedocs.io/en/latest/rest.html) could be better. 

- [ ] Integrate [sphinxcontrib-openapi](https://sphinxcontrib-openapi.readthedocs.io/) into our Sphinx documentation setup.
- [ ] Use the tool to render our existing [swagger file](https://github.com/dagu-dev/dagu/blob/main/swagger.yaml) into a more user-friendly format.

**Comment by gedw99** [comment]
https://github.com/deepmap/oapi-codegen ?

**Comment by yohamta** [comment]
That seems flexible than go-swagger. I'm a bit unsure if it's worth to switch at this moment tho.
