### ISSUE TITLE
docker run: exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by pommetjehorlepiep** [dagu-dev/dagu#524]
```
docker run \
--rm \
-p 8080:8080 \
-v $HOME/.dagu/dags:/home/dagu/.dagu/dags \
-v $HOME/.dagu/data:/home/dagu/.dagu/data \
-v $HOME/.dagu/logs:/home/dagu/.dagu/logs \
yohamta/dagu:latest
Unable to find image 'yohamta/dagu:latest' locally
latest: Pulling from yohamta/dagu
c30352492317: Pull complete
1589b2e124fa: Pull complete
4f4fb700ef54: Pull complete
7a3427f0747c: Pull complete
Digest: sha256:c770f056f04daf116e15e9d694f3240608c89ec7cb15e06d49eba657371740cb
Status: Downloaded newer image for yohamta/dagu:latest
exec /bin/sh: exec format error
```

Docker version
```
Client:
Version:           24.0.7
API version:       1.43
Go version:        go1.21.3
Git commit:        afdd53b4e3
Built:             Sun Oct 29 15:42:02 2023
OS/Arch:           linux/amd64
Context:           default

Server:
Engine:
Version:          24.0.7
API version:      1.43 (minimum version 1.12)
Go version:       go1.21.3
Git commit:       311b9ff0aa
Built:            Sun Oct 29 15:42:02 2023
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          v1.7.11
GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba.m
runc:
Version:          1.1.11
GitCommit:
docker-init:
Version:          0.19.0
GitCommit:        de40ad0
```

**Comment by adocampo** [comment]
same issue here
```
# docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.3
 Git commit:        afdd53b4e3
 Built:             Sun Oct 29 15:42:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       311b9ff0aa
  Built:            Sun Oct 29 15:42:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.6
  GitCommit:        091922f03c2762540fd057fba91260237ff86acb.m
 runc:
  Version:          1.1.9
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Forum1877621** [comment]
If this is fixed can you make a new release? I'm still getting this exec format error.

**Comment by yohamta** [comment]
@Forum1877621 Sorry for the late response. I've just published the latest docker image. Can you please check if this is fixed, when you have a chance?
https://hub.docker.com/r/yohamta/dagu
image: yohamta/dagu@latest

**Comment by Forum1877621** [comment]
I'm getting the same error
```
[+] Running 2/0
 ✔ Network dagu_default   Created0.0s
 ✔ Container dagu-dagu-1  Created0.0s
Attaching to dagu-1
dagu-1  | exec /bin/sh: exec format error
dagu-1 exited with code 1
```

Any ideas?

Here's my compose file
```
version: '3.8'

services:
  dagu:
    image: yohamta/dagu:latest
    ports:
      - "9999:8080"
    volumes:
      - "~/docker_data/dagu/dags:/home/dagu/.dagu/dags"
      - "~/docker_data/dagu/data:/home/dagu/.dagu/data"
      - "~/docker_data/dagu/logs:/home/dagu/.dagu/logs"
    restart: no
```

**Comment by yohamta** [comment]
Thanks @Forum1877621,  would you mind if I ask which platform do you use for running the container?
This is the docker command to build the image
https://github.com/dagu-dev/dagu/blob/cc1b134569852c55bcb0771ac4f2cf869b988006/Makefile#L10

**Comment by Forum1877621** [comment]
64 bit Ubuntu

Linux 6.5.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux

**Comment by JadRho** [comment]
Manually building the image is working so the issue may be in the layers.

Inspecting yohamta/dagu:latest the first line is
`FROM b09314aec293bcd`

further inspecting this image id (b09314aec293bcd9a8ee5e643539437b3846f9e5e55f79e282e5f67e3026de5e) we find that the base layer is for arm64
`/var/lib/containers/storage/overlay/b09314aec293bcd9a8ee5e643539437b3846f9e5e55f79e282e5f67e3026de5e/diff/bin/busybox: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, BuildID[sha1]=044386987bb479314c5fb9741167734e720bcc3e, stripped`

Seems the build system is using the wrong alpine image for linux/amd64

**Comment by yohamta** [comment]
Thanks for checking manual build. I think we can fix the Dockerfile to build binary instead of using binaries on GitHub release page.

**Comment by JadRho** [comment]
The problem is not with dagu. It is with the underlaying alpine image.
Somehow from the
> https://github.com/dagu-dev/dagu/blob/main/Dockerfile#L2
The variable BUILDPLATFORM seems to be wrong or docker is pulling the wrong alpine base

**Comment by yohamta** [comment]
Thanks for the comment. I greatly appreciate if anyone could help us fix this 🙂

**Comment by UnknownX1** [comment]
@Forum1877621 
You can add this line to the compose file.
```command: dagu server```

**Comment by yohamta** [comment]
I have just fixed the issue. Sorry for taking a long time.

**Comment by paspo** [comment]
Thanks.
Can you please create a new release?
This will trigger the creation of new container images in docker hub, fixing currently unusable images.

**Comment by yohamta** [comment]
I have added a fix only for the Dockerfile and rebuilt the image. Can you please try the latest image and see if it’s fixed?

**Comment by paspo** [comment]
I already tried, and I tried again.
I can confirm that the dagu binary is amd64 while the base image (alpine) is aarch64.

`latest` tag, pushed 21 days ago: [see docker hub](https://hub.docker.com/layers/yohamta/dagu/latest/images/sha256-b9b9fa3ca0274f890adb28dce5237e28090259d2981ef5756c6c5dbaf9e71cdc?context=explore)

**Comment by paspo** [comment]
```sh
# pull image
docker pull yohamta/dagu:latest

# create temporary container
docker create --name dagu  yohamta/dagu:latest

# create temporary directory
mkdir ~/delme ; cd ~/delme

# export the container filesystem
docker export dagu | tar xv

# check base image architecture
cat etc/apk/arch 

# check binary architecture
file usr/local/bin/dagu
```

**Comment by yohamta** [comment]
Hey, I've recently migrated the container image to GitHub. Can you please give it a try?

ghcr.io/dagu-dev/dagu:latest

**Comment by paspo** [comment]
same:
```sh
12:15:45 me@mypc:~/ee$ cat etc/apk/arch 
aarch64
12:15:49 me@mypc:~/ee$ file usr/local/bin/dagu 
usr/local/bin/dagu: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Zd3PfvCj3nrg7LF2HBdD/nTozrA-wclTAQf49Jx9f/2SQrrDehmM4LtGQA8S2l/iM59oNhz5SqDcB9XyBW1, with debug_info, not stripped
```

**Comment by yohamta** [comment]
@paspo Sorry for the inconvenience. I've just pushed the docker image for 5 more architectures:
https://github.com/orgs/dagu-dev/packages/container/package/dagu

Can you please try again?
```
docker rmi -f ghcr.io/dagu-dev/dagu:latest
docker run --rm ghcr.io/dagu-dev/dagu:latest dagu start-all
```
Or 
```
docker run --platform=<your platform> --rm ghcr.io/dagu-dev/dagu:latest dagu start-all
```

**Comment by paspo** [comment]
same problem as before... with this image

```sh
docker images 
REPOSITORY                              TAG       IMAGE ID       CREATED        SIZE
ghcr.io/dagu-dev/dagu                   latest    9cd3319a80a8   5 hours ago    47.2MB
```

**Comment by yohamta** [comment]
@paspo Oops, I think I finally found the cause in the Dockerfile and just pushed the fixed image. Sorry, but could you please try it again?

**Comment by paspo** [comment]
`ghcr.io/dagu-dev/dagu:latest` seems ok now.

If the official container repository is now ghcr, you should evaluate to update docs everywhere; like https://dagu.dev/installation/

thanks again

**Comment by yohamta** [comment]
Glad that it's fixed. Thanks for the confirmation. Yeah, I've forgotten about the docs, will update later.
