### ISSUE TITLE
make gen-pb not working

### ISSUE THREAD

**Issue by codinggeeks06** [dagu-dev/dagu#526]
While compiling on air gapped system, we are getting error when gen-pb target is being run.
following is the error:
google/protobuf/any.proto was not found or had errors
google/protobuf/duration.proto was not found or had errors

If we try to set proto_path to exact path, it gives following error:

protoc-gen-go: Invalid go import path "types" for google/protobuf/any.proto

The import path must contain at alteast one period('.') or forward slash ('/') character.

Please help

Kriyanshi

**Comment by yohamta** [comment]
I've removed all dependencies on pb. It should be resolved now.
