### ISSUE TITLE
Cron job doesn't work

### ISSUE THREAD

**Issue by HtcOrange** [dagu-dev/dagu#530]
![image](https://github.com/dagu-dev/dagu/assets/45788647/ff0d0791-f607-40d5-b378-10ba713a9219)
I add a dag with cron expression，it works after I clicked "run".But there is nothing happened after 1 minutes!!!!!!!

**Comment by yohamta** [comment]
Hello @HtcOrange , can I ask which command do you use to launch the Dagu's web UI?
For scheduled job, you will need to launch `dagu scheduler` process unless you are using `dagu start-all` command.

**Comment by HtcOrange** [comment]
my command is:
`dagu start-all -s 0.0.0.0 -p 8885`
but it seems that when I add a new cron dag, it ran only once(But I need it run every minute). Then I restarted dagu by the command below, it started to run in every minute. Finally, I added a new cron dag after I restarted dagu, the running phenomenon was still the same: it only ran once and did not run at a scheduled time of once per minute.
So, how should I automatically start the scheduler, does command "start-all" works?

**Comment by yohamta** [comment]
@HtcOrange 
The `start-all` command should work. I've just tried on my PC and it works fine.
Could you please check the log if there's any? Also, please try running `dagu scheduler` alone instead of `start-all` and see if it works.

**Comment by HtcOrange** [comment]
@yohamta 
I saw the log, as we can see, the four dags can be scheduled
![image](https://github.com/dagu-dev/dagu/assets/45788647/f508ceda-17cf-40ee-a9fc-e88234ba7886)

but, there are still other dags are not scheduled. The command is "dagu scheduler -d ./"
![image](https://github.com/dagu-dev/dagu/assets/45788647/fb54a186-1fe2-434f-921f-cc9137a9107a)

**Comment by HtcOrange** [comment]
@yohamta So, it means that the scheduler only run the existed dags when it started? Why the scheduler can't find the dags which are added after the scheduler started......

**Comment by yohamta** [comment]
I've just tested for adding a new DAG after launching the scheduler but it works fine as expected.
The scheduler process normally detect any changes or new files in DAGs dir, but except for a case where your storage does not allow for watching event, for example, NFS. Can I ask you what kind of storage do you use for the DAGs dir?

**Comment by yohamta** [comment]
I think the issue is solved thanks to the PR.
