### ISSUE TITLE
Document seems outdated？

### ISSUE THREAD

**Issue by k29913x** [dagu-dev/dagu#545]
The Document context and actual code is NOT congruous.
For example, Code Structure is different from current version.
It seems that some code restructure was made but doc remains unchanged.
It would be great if this can be fixed!
![image](https://github.com/dagu-dev/dagu/assets/6055214/edb35108-fe97-4e10-b4a2-1af5b516b2da)

**Comment by yohamta** [comment]
This issue is fixed now. Thanks for raising this issue.
