### ISSUE TITLE
Fix linter errors

### ISSUE THREAD

**Issue by yohamta** [dagu-dev/dagu#553]
How to install golangci-lint: https://golangci-lint.run/welcome/install/
Then you can run the following command to see lint errors.
```
make lint
```

**Comment by Kiyo510** [comment]
Hi, @yohamta 
Can I work on this issue?

**Comment by Kiyo510** [comment]
@yohamta 
I am already working on this issue.
Thank you for your continued cooperation!

**Comment by yohamta** [comment]
@Kiyo510 Thank you so much for helping us solve this issue.
