### ISSUE TITLE
Install dagu '/usr/local/bin'

### ISSUE THREAD

**Issue by arky** [dagu-dev/dagu#566]
It is recommended to install dagu to `/usr/local/bin` not the current directory.  Download the archive to `/tmp` and then copy it to `/usr/local/bin` if `sudo` is available.  

https://github.com/dagu-dev/dagu/blob/d0938f1198e0c10b7c2ddc7187c6fd43448a542f/scripts/downloader.sh#L6

https://github.com/dagu-dev/dagu/blob/d0938f1198e0c10b7c2ddc7187c6fd43448a542f/scripts/downloader.sh#L35

**Comment by yohamta** [comment]
Thanks for the suggestion, now the issue is fixed.
