### ISSUE TITLE
Empty config.yaml casues tasks to not run

### ISSUE THREAD

**Issue by mdgreenwald** [dagu-dev/dagu#567]
Steps to repeat:

```bash
mv .dagu/config.yaml .dagu/backup.config.yaml
touch .dagu/config.yaml
dagu start-all
```

Now, try to run any task, even a simple `command: echo hello` will result in the bug.

Error Message:
```
2024/05/17 15:13:46 EOF
2024/05/17 15:13:46 starting a DAG failed. exit status 1
```

Additionally a `config.yaml` with all configuration lines commented out will also cause this bug.

Might be nicer to get a warning; `WARN: empty config.yaml` or a clearer error message; `ERROR: empty config.yaml`

Thanks!

**Comment by yohamta** [comment]
Now it's fixed in v1.13.0
